# Available images https://cirrus-ci.org/guide/macOS/
macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

task:
  name: 'install bitrise cli'
  script:
  - 'brew update && brew install bitrise'
  - 'bitrise setup'
  - 'bitrise run primary'

#task:
#  name: 'bitrise run primary'
#  depends_on:
#  - 'install bitrise cli'
#  script: 'bitrise run primary'
