osx_instance:
  image: mojave-xcode-10.1

task:
  name: 'install bitrise cli'
  script:
  - 'brew update && brew install bitrise'
  - 'bitrise setup'
  - 'bitrise run primary'

#task:
#  name: 'bitrise run primary'
#  depends_on:
#  - 'install bitrise cli'
#  script: 'bitrise run primary'
