workflows:
  my-workflow:
    scripts:
      - name: CLI setup
        script: |
          set -ex
          brew update && brew install bitrise
          bitrise setup
      - name: Run
        script: |
          set -ex
          bitrise run primary
