name: Birise run primary

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    env:
      DEVELOPER_DIR: '/Applications/Xcode_11.2.app/Contents/Developer'
      CI: 'true'

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode Version
      run: xcode-select --switch="$DEVELOPER_DIR"
    - name: Xcode simulators
      run: xcversion simulators
    - name: Install
      run: brew update && brew install bitrise && bitrise setup
    - name: Run
      run: bitrise run primary
