name: Xcode Version

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer 

    steps:
    - uses: actions/checkout@v1
    - name: available xcodes
      run: ls -alh /Applications | grep -i 'Xcode*'
    - name: xcodebuild version
      run: xcodebuild -version
